name: Main

on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - 'docs/**'

  # This cannot work because the 'paths' required one path to trigger the action + the negative one.
  # https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#example-including-and-excluding-paths
#  pull_request:
#    paths:
#      - '!docs/**'

jobs:

  main:
    name: Main Process
    runs-on: ubuntu-latest
    env:
      GO_VERSION: 1.17
      CGO_ENABLED: 0

    steps:

      # https://github.com/marketplace/actions/setup-go-environment
      - name: Set up Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      # https://github.com/marketplace/actions/checkout
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Make
        run: make
